apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: naive-panic
spec:
  selector:
    app: client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort