apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-listener
  labels:
    app: events-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-listener
  template:
    metadata:
      labels:
        app: events-listener
    spec:
      containers:
        - name: events-listener
          image: armanmasoumi/gophercon-events-listener:6
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/rabbitmq-admin
              name: rabbitmq-admin
              readOnly: true
          resources:
            requests:
              cpu: 0.1
              memory: "100Mi"
            limits:
              cpu: 0.5
              memory: "100Mi"
      volumes:
        - name: rabbitmq-admin
          secret:
            secretName: rabbitmq-admin
