apiVersion: v1
data:
  pass: X0x0bTM2RWdTUFhMc2VvSVV3a0xjUkFZRVFoN2ZHYmo=
  user: ZGVmYXVsdF91c2VyXzRGMUdmdEgyR05VTUx4aXN3MDc=
  address: ZGVmaW5pdGlvbi50ZXN0LXJhYmJpdG1xLnN2Yw==
kind: Secret
metadata:
  name: rabbitmq-admin
type: Opaque