apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: naive
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: grpc
      protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort